### ISSUE TITLE
Can't disable coverage analysis when mocha tests fail

### ISSUE THREAD

**Issue by iongion** [jmcriffey/babel-istanbul#62]
I am sorry for leaving this here, it is more of a question.
I run the command line this:
```
node_modules\.bin\babel-node.cmd ./node_modules/babel-istanbul/lib/cli cover node_modules/mocha/bin/_mocha -- --compilers js:babel-core/register --bail --sort --reporter spec --require test/bootstrap.js --recursive test/unit/**/**/*.spec.js
```

Can I prevent istanbul for doing the coverage analysis when the mocha tests fail ?
It just pollutes the output with something that most of the times is not useful if they fail.

**Comment by jmcriffey** [comment]
@iongion I'm actually not sure. My gut says that it is not currently possible. I would maybe open an issue with `istanbul` to see if that is supported or a future feature.
