### ISSUE TITLE
babel-istanbul not working: SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by Moezalez** [jmcriffey/babel-istanbul#65]
When trying to run:

`babel-istanbul cover _mocha test/**.js`

I get:

```
import { toCamelCase, toSnakeCase } from '../src'
^^^^^^
SyntaxError: Unexpected reserved word
```

**Comment by jmcriffey** [comment]
You'll need to run your tests with babel-node. Install babel-cli and try this command:

`babel-node babel-istanbul cover _mocha test/*.js`

**Comment by Moezalez** [comment]
Thanks, seems to have fixed it.

Though, tt seems to work in another library without babel-node. Thats odd.

**Comment by Moezalez** [comment]
@jmcriffey  actually it is not working. 

Trying your solution I got:
`Error: Cannot find module '/Users/Moritz/case-converter/babel-istanbul'`

Then tried: `babel-node node_modules/babel-istanbul cover _mocha test/**.js`

Which just seems to do nothing.

**Comment by jmcriffey** [comment]
Yeah I forgot you need to point to the bin. 

`babel-node node_modules/.bin/babel-istanbul cover _mocha test/*.js`
