### ISSUE TITLE
Upgrade to Babel 7

### ISSUE THREAD

**Issue by hershmire** [jmcriffey/babel-istanbul#85]
Are there any plans to upgrade to Babel 7 now that it's officially released?

**Comment by jmcriffey** [comment]
This project actually hasn't been maintained in quite awhile. It was created during a time when `istanbul` itself did not have good support for transpiled code. I believe that `istanbul` is now fully up to date and should work with babel given some configuration. You'll probably want to install the `nyc` command line client, which handles a bunch of that stuff for you.

https://istanbul.js.org/

**Comment by hershmire** [comment]
Ok, thanks. That's what I assumed but wanted to verify.
